name = "drive-pro"
main = "worker.js"
compatibility_date = "2024-05-24"

[vars]
GOOGLE_CLIENT_ID = "1051411859059-ejo6a7g8aee7e9i45h569a66otg8ru9j.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://smti.uk/drive-pro/api/auth-callback"

[[d1_databases]]
binding = "DB"
database_name = "drive-pro"
database_id = "2dee5e98-bf06-4aa3-991d-129ef43b1cc1"
